# Generated by Django 3.1 on 2022-03-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=55)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('text', models.TextField(max_length=100)),
            ],
        ),
    ]
